// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CheckBinary checks if a binary exists for a given MCP
 * @param {string} mcpId
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckBinary(mcpId) {
    return $Call.ByID(1351409650, mcpId);
}

/**
 * ClosePanel closes the current panel (this might be called from a panel window)
 * @returns {$CancellablePromise<void>}
 */
export function ClosePanel() {
    return $Call.ByID(1977574899);
}

/**
 * DeleteCredential removes a credential from the macOS Keychain.
 * @param {string} key
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCredential(key) {
    return $Call.ByID(2865671487, key);
}

/**
 * DownloadBinary downloads a binary from a URL and saves it locally
 * @param {string} mcpId
 * @param {string} url
 * @returns {$CancellablePromise<string>}
 */
export function DownloadBinary(mcpId, url) {
    return $Call.ByID(3375380784, mcpId, url);
}

/**
 * ExchangeToken performs a client_credentials exchange locally in the Wails backend.
 * @param {string} mcpId
 * @param {string} tokenUrl
 * @param {string} clientId
 * @param {string} clientSecret
 * @param {string[]} scopes
 * @returns {$CancellablePromise<string>}
 */
export function ExchangeToken(mcpId, tokenUrl, clientId, clientSecret, scopes) {
    return $Call.ByID(441194157, mcpId, tokenUrl, clientId, clientSecret, scopes);
}

/**
 * ExecuteBinary runs a local binary, performs MCP handshake, and calls the tool
 * @param {string} mcpId
 * @param {string} toolName
 * @param {{ [_ in string]?: any }} args
 * @param {string} apiKey
 * @param {string} envVarName
 * @returns {$CancellablePromise<string>}
 */
export function ExecuteBinary(mcpId, toolName, args, apiKey, envVarName) {
    return $Call.ByID(4135588741, mcpId, toolName, args, apiKey, envVarName);
}

/**
 * ExecuteRemoteTool calls a specific tool on a remote HTTP MCP server.
 * @param {string} mcpId
 * @param {string} endpoint
 * @param {string} token
 * @param {string} toolName
 * @param {{ [_ in string]?: any }} args
 * @returns {$CancellablePromise<string>}
 */
export function ExecuteRemoteTool(mcpId, endpoint, token, toolName, args) {
    return $Call.ByID(3928087584, mcpId, endpoint, token, toolName, args);
}

/**
 * ExecuteSystemCommand executes a macOS system command
 * @param {string} cmd
 * @returns {$CancellablePromise<string>}
 */
export function ExecuteSystemCommand(cmd) {
    return $Call.ByID(2648788270, cmd);
}

/**
 * GetCredential retrieves a credential from the macOS Keychain.
 * Returns empty string if not found (no error).
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetCredential(key) {
    return $Call.ByID(514420326, key);
}

/**
 * GetInstalledApps returns a list of installed macOS applications
 * @returns {$CancellablePromise<string>}
 */
export function GetInstalledApps() {
    return $Call.ByID(2510770099);
}

/**
 * Greet returns a greeting for the given name
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(2659711170, name);
}

/**
 * HasCredential returns true if a credential exists for the given key.
 * @param {string} key
 * @returns {$CancellablePromise<boolean>}
 */
export function HasCredential(key) {
    return $Call.ByID(2456175666, key);
}

/**
 * ListTools queries an MCP binary for exactly what tools and schemas it supports dynamically.
 * @param {string} mcpId
 * @param {string} apiKey
 * @param {string} envVarName
 * @returns {$CancellablePromise<string>}
 */
export function ListTools(mcpId, apiKey, envVarName) {
    return $Call.ByID(3282129816, mcpId, apiKey, envVarName);
}

/**
 * ListToolsRemote fetches the tool schema from a remote HTTP MCP server.
 * @param {string} mcpId
 * @param {string} endpoint
 * @param {string} token
 * @returns {$CancellablePromise<string>}
 */
export function ListToolsRemote(mcpId, endpoint, token) {
    return $Call.ByID(3932702158, mcpId, endpoint, token);
}

/**
 * OpenOAuthBrowser opens the system browser to the given URL.
 * Used to initiate the OAuth2 flow: the user logs in, the cloud server
 * exchanges the code for tokens, then redirects to octomus://oauth/callback?token=...
 * which is intercepted by the registered URL scheme handler.
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenOAuthBrowser(url) {
    return $Call.ByID(2866941560, url);
}

/**
 * OpenOnboarding opens the Onboarding panel
 * @returns {$CancellablePromise<void>}
 */
export function OpenOnboarding() {
    return $Call.ByID(2065255028);
}

/**
 * OpenSettings opens the Settings panel
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettings() {
    return $Call.ByID(2024983644);
}

/**
 * SaveCredential saves a credential (token, API key, etc.) in the macOS Keychain.
 * key is typically "{mcpId}_token" or "{mcpId}_refresh_token".
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SaveCredential(key, value) {
    return $Call.ByID(3204725985, key, value);
}

/**
 * StopBinary kills a running MCP binary process
 * @param {string} mcpId
 * @returns {$CancellablePromise<void>}
 */
export function StopBinary(mcpId) {
    return $Call.ByID(672055108, mcpId);
}

/**
 * ToggleWindow hides or shows the main window
 * @returns {$CancellablePromise<void>}
 */
export function ToggleWindow() {
    return $Call.ByID(1210966453);
}
