FROM golang:alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o controlplane cmd/controlplane/main.go

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/controlplane .

EXPOSE 8081
EXPOSE 50051

CMD ["./controlplane"]
