// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckBinary(arg1:string):Promise<boolean>;

export function DownloadBinary(arg1:string,arg2:string):Promise<string>;

export function ExecuteBinary(arg1:string,arg2:string,arg3:Record<string, any>,arg4:string,arg5:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ListTools(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ToggleWindow():Promise<void>;
