// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckBinary(arg1) {
  return window['go']['main']['App']['CheckBinary'](arg1);
}

export function DownloadBinary(arg1, arg2) {
  return window['go']['main']['App']['DownloadBinary'](arg1, arg2);
}

export function ExecuteBinary(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ExecuteBinary'](arg1, arg2, arg3, arg4, arg5);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListTools(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListTools'](arg1, arg2, arg3);
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
