// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckBinary(arg1:string):Promise<boolean>;

export function DeleteCredential(arg1:string):Promise<void>;

export function DownloadBinary(arg1:string,arg2:string):Promise<string>;

export function ExchangeToken(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<string>;

export function ExecuteBinary(arg1:string,arg2:string,arg3:Record<string, any>,arg4:string,arg5:string):Promise<string>;

export function ExecuteRemoteTool(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<string, any>):Promise<string>;

export function ExecuteSystemCommand(arg1:string):Promise<string>;

export function GetCredential(arg1:string):Promise<string>;

export function GetInstalledApps():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HasCredential(arg1:string):Promise<boolean>;

export function ListTools(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ListToolsRemote(arg1:string,arg2:string,arg3:string):Promise<string>;

export function OpenOAuthBrowser(arg1:string):Promise<void>;

export function SaveCredential(arg1:string,arg2:string):Promise<void>;

export function StopBinary(arg1:string):Promise<void>;

export function ToggleWindow():Promise<void>;
